### ISSUE TITLE
无法显示人的图片

### ISSUE THREAD

**Issue by zrll12** [Illyasviels/Live2DonWeb#1]
实际效果：
![default](https://user-images.githubusercontent.com/46812903/52521994-a2e58200-2cba-11e9-9c47-4da87c2e4d26.png)

**Comment by tiltysola** [comment]
打开开发者人员工具，打开Network选项卡，刷新页面，查看是什么问题。

**Comment by zrll12** [comment]
但是你给的那个网站上就没有，下载的html文件打开后显示报错Access to XMLHttpRequest at 'file:/models/message.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.和Access to XMLHttpRequest at 'file:/models/illyasviel/illyasviel.model.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

**Comment by tiltysola** [comment]
因为浏览器默认禁用了file协议下的cors，你需要把他上传到服务器上才能用。
